import { supabase } from '@/integrations/supabase/client';

/**
 * Extracts mentioned user IDs from HTML content generated by Tiptap mention extension
 * @param htmlContent The raw HTML content from the editor
 * @returns Array of unique user IDs mentioned in the text
 */
export function extractMentionedUserIds(htmlContent: string): string[] {
  const mentionRegex = /data-type="mention"[^>]*data-id="([^"]+)"/g;
  const ids = new Set<string>();
  
  let match;
  while ((match = mentionRegex.exec(htmlContent)) !== null) {
    if (match[1]) {
      ids.add(match[1]);
    }
  }
  
  return Array.from(ids);
}

/**
 * Parses HTML content for mentions and sends a notification to each mentioned user
 * @param htmlContent The content of the post/comment
 * @param senderName The name of the user who made the post
 * @param context The context where this mention happened (e.g., 'Comunidade', 'Fórum')
 */
export async function sendMentionNotifications(
  htmlContent: string, 
  senderName: string, 
  context: string = 'plataforma'
) {
  try {
    const mentionedIds = extractMentionedUserIds(htmlContent);
    
    if (mentionedIds.length === 0) return;

    // Filter out the sender themselves if they mentioned themselves
    // To do this, we need the current user's ID. Let's fetch it from auth.
    const { data: { user } } = await supabase.auth.getUser();
    
    const validRecipients = mentionedIds.filter(id => id !== user?.id);
    
    if (validRecipients.length === 0) return;

    const notifications = validRecipients.map(recipientId => ({
      title: "Nova menção!",
      content: `${senderName || 'Alguém'} mencionou você em uma publicação na ${context}.`,
      audience: "direct",
      recipient_id: recipientId,
      sent_at: new Date().toISOString(), // immediately show up in the feed
    }));

    const { error } = await supabase
      .from('notifications')
      .insert(notifications);

    if (error) {
      console.error("Error sending mention notifications:", error);
    }
  } catch (error) {
    console.error("Failed to process mentions:", error);
  }
}
